/**
 * Export live marketing-site ingest keys from Vercel → Neon-ready SQL.
 *
 * IMPORTANT: Do NOT run this inside Cursor's integrated terminal.
 * Cursor redacts secret values to the literal string "[SENSITIVE]" in pulled
 * .env files. Use Windows Terminal / external PowerShell instead.
 *
 * Sites:
 *   - cabin-services                  → PORTAL_INGEST_KEY → cabin-services
 *   - smoky-peak-integrated-systems   → PORTAL_INGEST_KEY → integrated-systems
 *   - smokypeakservices-tech          → INGEST_CLIENT_SECRET → integrated-systems
 *
 * Usage (external PowerShell, repo root, `vercel` logged in):
 *   Remove-Item -Recurse -Force .tmp-ingest-export -ErrorAction SilentlyContinue
 *   npm run export:marketing-ingest-keys
 *
 * Writes (gitignored):
 *   .tmp-ingest-export/insert-ingest-keys.sql
 *   .tmp-ingest-export/*.env
 */
import { createHash } from "node:crypto";
import {
  mkdirSync,
  writeFileSync,
  readFileSync,
  existsSync,
  rmSync,
} from "node:fs";
import { join } from "node:path";
import { spawnSync } from "node:child_process";

const OUT = join(process.cwd(), ".tmp-ingest-export");
const SCOPE = "ryank-3313s-projects";
const REDACTED = "[SENSITIVE]";

type Site = {
  project: string;
  envFile: string;
  keyVar: string;
  urlVar: string;
  divisionSlug: string;
  label: string;
};

const SITES: Site[] = [
  {
    project: "cabin-services",
    envFile: "cabin.env",
    keyVar: "PORTAL_INGEST_KEY",
    urlVar: "PORTAL_INGEST_URL",
    divisionSlug: "cabin-services",
    label: "Cabin Services website",
  },
  {
    project: "smoky-peak-integrated-systems",
    envFile: "is.env",
    keyVar: "PORTAL_INGEST_KEY",
    urlVar: "PORTAL_INGEST_URL",
    divisionSlug: "integrated-systems",
    label: "Integrated Systems website",
  },
  {
    project: "smokypeakservices-tech",
    envFile: "parent.env",
    keyVar: "INGEST_CLIENT_SECRET",
    urlVar: "INGEST_SERVER_URL",
    divisionSlug: "integrated-systems",
    label: "Parent smokypeak.tech (INGEST_CLIENT_SECRET)",
  },
];

function hashKey(raw: string) {
  return createHash("sha256").update(raw, "utf8").digest("hex");
}

function parseEnv(filePath: string): Record<string, string> {
  const out: Record<string, string> = {};
  if (!existsSync(filePath)) return out;
  for (const line of readFileSync(filePath, "utf8").split(/\r?\n/)) {
    if (!line || line.trim().startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const k = line.slice(0, eq).trim();
    let v = line.slice(eq + 1).trim();
    if (
      (v.startsWith('"') && v.endsWith('"')) ||
      (v.startsWith("'") && v.endsWith("'"))
    ) {
      v = v.slice(1, -1);
    }
    out[k] = v;
  }
  return out;
}

function assertNotCursorTerminal() {
  const markers = [
    process.env.CURSOR_TRACE_ID,
    process.env.CURSOR_AGENT,
    process.env.CURSOR_SESSION_ID,
    process.env.COMPOSER_SESSION_ID,
  ].filter(Boolean);
  if (markers.length > 0) {
    console.warn(
      "WARNING: Cursor agent/session env detected. Secret pulls may be rewritten to [SENSITIVE].",
    );
    console.warn(
      "If this fails, re-run in Windows Terminal (Win+X → Terminal), not Cursor.",
    );
  }
}

function pull(project: string, dest: string) {
  if (existsSync(dest)) rmSync(dest, { force: true });
  const cmd = `npx vercel env pull "${dest}" --environment production --project ${project} --scope ${SCOPE} --yes`;
  const r = spawnSync(cmd, {
    encoding: "utf8",
    shell: true,
    env: {
      ...process.env,
      // Avoid agent/non-interactive behaviors that may redact secrets.
      CURSOR_TRACE_ID: "",
      CURSOR_AGENT: "",
      CURSOR_SESSION_ID: "",
      COMPOSER_SESSION_ID: "",
    },
  });
  if (r.status !== 0) {
    console.error(r.stdout || r.stderr);
    throw new Error(`vercel env pull failed for ${project}`);
  }
  if (!existsSync(dest)) {
    throw new Error(`vercel env pull did not create ${dest}`);
  }
}

assertNotCursorTerminal();

if (existsSync(OUT)) {
  rmSync(OUT, { recursive: true, force: true });
  console.log("Removed stale .tmp-ingest-export/");
}
mkdirSync(OUT, { recursive: true });

const sql: string[] = [
  "-- Marketing ingest keys → PII ingest_key (sha256 hashes only)",
  "-- Generated by scripts/export-marketing-ingest-keys.ts",
  "-- Portal auth: createHash('sha256').update(raw).digest('hex')",
  "",
];

const seenHash = new Set<string>();

console.log("Pulling Vercel production env…");
for (const site of SITES) {
  const dest = join(OUT, site.envFile);
  pull(site.project, dest);
  const env = parseEnv(dest);
  const raw = (env[site.keyVar] ?? "").trim();
  const url = (env[site.urlVar] ?? "").trim();
  if (!raw) {
    console.error(`MISSING ${site.keyVar} on ${site.project}`);
    continue;
  }
  if (raw === REDACTED || raw.includes(REDACTED)) {
    throw new Error(
      [
        `Env value for ${site.keyVar} on ${site.project} is literally "${REDACTED}".`,
        "That is Cursor (or another wrapper) redacting secrets into the file — not the real Vercel value.",
        "",
        "Fix:",
        "  1. Close this script.",
        "  2. Open Windows Terminal (not Cursor).",
        "  3. cd into the repo.",
        "  4. Remove-Item -Recurse -Force .tmp-ingest-export",
        "  5. npm run export:marketing-ingest-keys",
      ].join("\n"),
    );
  }
  const keyHash = hashKey(raw);
  const keyPrefix = raw.slice(0, Math.min(12, raw.length));
  console.log(
    `${site.project}: ${site.keyVar} prefix=${keyPrefix}… hash=${keyHash.slice(0, 12)}… url=${url || "(none)"}`,
  );

  if (seenHash.has(keyHash)) {
    console.warn(
      `  ! same keyHash already queued — unique(keyHash) means only one Neon row can exist for this raw key.`,
    );
  }
  seenHash.add(keyHash);

  const label = site.label.replace(/'/g, "''");
  sql.push(`-- ${site.project} / ${site.keyVar} → ${site.divisionSlug}`);
  sql.push(
    `INSERT INTO ingest_key (id, "divisionId", label, "keyHash", "keyPrefix", "createdAt")`,
  );
  sql.push(
    `SELECT gen_random_uuid()::text, d.id, '${label}', '${keyHash}', '${keyPrefix.replace(/'/g, "''")}', NOW()`,
  );
  sql.push(`FROM division d WHERE d.slug = '${site.divisionSlug}'`);
  sql.push(
    `AND NOT EXISTS (SELECT 1 FROM ingest_key k WHERE k."keyHash" = '${keyHash}');`,
  );
  sql.push("");
}

const sqlPath = join(OUT, "insert-ingest-keys.sql");
writeFileSync(sqlPath, sql.join("\n"), "utf8");
console.log(`\nWrote ${sqlPath}`);
console.log(
  "Run that SQL on the PII Neon database (Division rows must exist). Do not commit .tmp-ingest-export/.",
);
